services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "5000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      EVENT_HUB_CONNECTION_STRING: Endpoint=sb://evh-dev-dados-auditoria.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={key}
      EVENT_HUB_NAME: auditoria
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import/
      - ./keycloak/providers:/opt/keycloak/providers/
    command: ["start-dev", "--import-realm","--verbose"]
    networks:
      - app-network

  keycloak-authorization-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-authorization-api
    depends_on:
      - keycloak
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://*:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge